{% set name = "ryvencore-qt" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ryvencore-qt-{{ version }}.tar.gz
  sha256: 0be122713045782fe54a62d9a4ff74a82dd870c01846f0105fd60803fcbeb961

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<=3.10
  run:
    - pyside2
    - python >=3.6,<=3.10
    - qtpy
    - textdistance
    - ryvencore ==0.4.*
    - waiting

test:
  imports:
    - ryvencore_qt
    - ryvencore_qt.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leon-thomm/ryvencore-qt
  summary: Qt frontend for ryvencore; Library for building Visual Node Editors
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
