{% set name = "ryvencore-qt" %}
{% set version = "0.3.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ryvencore-qt-{{ version }}.tar.gz
  sha256: b3d35fbd2916d0c92a5d6c1e0dada00fdf264e2b14d84a9732a2751324b36fd8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pyside2
    - python >=3.6
    - qtpy
    - textdistance
    - ryvencore ==0.3.1.*
    - waiting

test:
  imports:
    - ryvencore_qt
    - ryvencore_qt.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leon-thomm/ryvencore-qt
  summary: Qt frontend for ryvencore; Library for building Visual Node Editors
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
