{% set name = "ryvencore-qt" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f24f883e931ebce76d1445ac0c4900399cc63b59e52693ae7a1b1783089dd068

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<=3.10
  run:
    - pyside2
    - python >=3.6,<=3.10
    - qtpy
    - textdistance
    - ryvencore ==0.5.*
    - waiting

test:
  imports:
    - ryvencore_qt
    - ryvencore_qt.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leon-thomm/ryvencore-qt
  summary: Qt frontend for ryvencore; Library for building Visual Node Editors
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
